### ISSUE TITLE
2.4 crashes immediately

### ISSUE THREAD

**Issue by TheJoffrey** [alexanderweiss/nova-prettier#95]
Hello,
When I start a new project on Nova or open a single file, Prettier just crashes.
I don't know how or why, but Prettier is now unusable.

My node version is 19.5.0. Thank you.

**Comment by alexanderweiss** [comment]
That's annoying. Can you share the logs from the extension console? It's under Extensions -> Extension Console (after you've enabled Extension Development in Preferences).

**Comment by TheJoffrey** [comment]
Hello and thank you for your reply.

Here it is:
```

Python Language Server connection closed unexpectedly: Error Domain=NSCocoaErrorDomain Code=4 "Le fichier « pyls » n’existe pas." UserInfo={NSFilePath=/usr/local/bin/pyls}
```

Which means that the file `pyls` doesn’t exist. So I tried to install pyls using pip3 but my issue isn’t gone.


De : Alexander Weiss ***@***.***>
Date : mercredi, 12 avril 2023 à 17:35
À : alexanderweiss/nova-prettier ***@***.***>
Cc : Joffrey Viémon ***@***.***>, Author ***@***.***>
Objet : Re: [alexanderweiss/nova-prettier] 2.4 crashes immediately (Issue #95)

That's annoying. Can you share the logs from the extension console? It's under Extensions -> Extension Console (after you've enabled Extension Development in Preferences).

**Comment by Hoody91** [comment]
I'm having a similar issue, however I'm unable to share the logs due to prettier crashing the extension service, let me know if there's anything else I can do to help.

<img width="275" alt="image" src="https://user-images.githubusercontent.com/68184680/231916553-ed05415b-2be7-469c-84e9-f076391d634f.png">

**Comment by jiaochangyang** [comment]
Hi. I am also experiencing the same issue. The extension crashes immediately on start up. When I look at the extension console, nothing is being logged. Thank you!

**Comment by alexanderweiss** [comment]
@TheJoffrey can you check in the extension console whether it's using the embedded prettier installation or your project prettier installation?

@jiaochangyang & @Hoody91 Could you try disabling and re-enabling the extension. And see if still happens when you close and open Nova then? I've seen this on my work machine too but after I did that I couldn't reproduce it.

**Comment by jiaochangyang** [comment]
Hi, I have tried disabling and re-enabling the extension as well as uninstalling/reinstalling the extension. It also consistently occurs across Nova restarts (force-quit + reopen).It crashes immediately in all cases.

**Comment by alexanderweiss** [comment]
@jiaochangyang I just released a new version again (2.5.0). I'm not sure if it fixes your issue but it might. I'm very curious if it does. If not I'll have to see how we can debug this further.

**Comment by Hoody91** [comment]
Hi, I've installed the latest version of the extension (2.5.0) and unfortunately I'm still getting the same crash, I also tried disabling/enabling as well as uninstalling/reinstalling the extension, all result in the same crash.

**Comment by Hoody91** [comment]
I've just tested @benwittorf's theory and I think I can add to it, when I start a blank project the extenion works fine, opening local projects works fine too, but when I try open a remote project it leads to the crash as well as opening a document outside a project also crashes.

**Comment by alexanderweiss** [comment]
Awesome that you figured that out @benwittorf! And thanks for confirming @Hoody91. Released 2.5.1 that should fix it.

**Comment by jiaochangyang** [comment]
Hi, I am no longer facing this crash as of 2.5.1. Thank you!!

**Comment by Hoody91** [comment]
I updated to 2.5.1 this morning and haven't had any issues all day, thanks for the help everyone.

**Comment by TheJoffrey** [comment]
Hi, yep it is working well now, thank you very much! :)
________________________________
De : Riley Hood ***@***.***>
Envoyé : Tuesday, April 18, 2023 11:16:50 AM
À : alexanderweiss/nova-prettier ***@***.***>
Cc : Joffrey Viémon ***@***.***>; Mention ***@***.***>
Objet : Re: [alexanderweiss/nova-prettier] 2.4 crashes immediately (Issue #95)


I updated to 2.5.1 this morning and haven't had any issues all day, thanks for the help everyone.
